version: '3.8'

services:
  uav-training:
    build: .
    container_name: uav-path-planning
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
    environment:
      - DISPLAY=:99
      - PYBULLET_EGL=1
      - MESA_GL_VERSION_OVERRIDE=3.3
    stdin_open: true
    tty: true
    
  tensorboard:
    build: .
    container_name: uav-tensorboard
    ports:
      - "6006:6006"
    volumes:
      - ./logs:/app/logs
    command: tensorboard --logdir=/app/logs --host=0.0.0.0 --port=6006
